export const actionTypes = {
    SET_VALUE: 'SET_VALUE',
    INCREMENT_VALUE: 'INCREMENT_VALUE',
    DECREMENT_VALUE: 'DECREMENT_VALUE',
    TOGGLE_COLOR: 'TOGGLE_COLOR',
    RESET_COLOR: 'RESET_COLOR',
    SET_SELECTED_OPTION: 'SET_SELECTED_OPTION',
    ADJUST_COUNT: 'ADJUST_COUNT',
    RESET_MULTIPLE_COUNT: 'RESET_MULTIPLE_COUNT',
    SAVE_DATA: 'SAVE_DATA',
    LOAD_DATA: 'LOAD_DATA',
    SET_INPUT_VALUE: 'SET_INPUT_VALUE',
    LOAD_DATA_FROM_DJANGO_SERVER: 'LOAD_DATA_FROM_DJANGO_SERVER'
};